name = "passkey-sveltekit"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = false
invocation_logs = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
